server:
  port: 8761
---
logging:
  level:
    com.netflix.discovery: 'OFF'
---
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
---
spring:
  profiles: cloud
server:
  port: ${PORT}
eureka:
  instance:
    registerWithEureka: false
    fetchRegistry: false
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    nonSecurePortEnabled: false
    securePortEnabled: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka/
    healthcheck:
      enabled: true
  server:
    enableSelfPreservation: false
